[package]
name = "launcher"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
reqwest = { version = "0.12", features = ["blocking", "rustls-tls"] }
zip = "0.6"
tempfile = "3"
windows-sys = { version = "0.52", features = ["Win32_System_Console", "Win32_Foundation"] }

[build-dependencies]
zip = "0.6"
winres = "0.1"
serde = { version = "1", features = ["derive"] }
toml = "0.8"
